version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: surya-store-fe
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080
    restart: unless-stopped
